/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronHourlyRouteImport } from './routes/api/cron/hourly'
import { Route as ApiIngestYoloRouteImport } from './routes/api/ingest/yolo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHourlyRoute = ApiCronHourlyRouteImport.update({
  id: '/api/cron/hourly',
  path: '/api/cron/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestYoloRoute = ApiIngestYoloRouteImport.update({
  id: '/api/ingest/yolo',
  path: '/api/ingest/yolo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/incidents': typeof IncidentsRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/subscribe': typeof SubscribeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/hourly': typeof ApiCronHourlyRoute
  '/api/ingest/yolo': typeof ApiIngestYoloRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/incidents': typeof IncidentsRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/subscribe': typeof SubscribeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/hourly': typeof ApiCronHourlyRoute
  '/api/ingest/yolo': typeof ApiIngestYoloRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/incidents': typeof IncidentsRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/subscribe': typeof SubscribeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/hourly': typeof ApiCronHourlyRoute
  '/api/ingest/yolo': typeof ApiIngestYoloRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/incidents'
    | '/locked'
    | '/login'
    | '/onboard'
    | '/platform'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/sites'
    | '/subscribe'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/hourly'
    | '/api/ingest/yolo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/incidents'
    | '/locked'
    | '/login'
    | '/onboard'
    | '/platform'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/sites'
    | '/subscribe'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/hourly'
    | '/api/ingest/yolo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/incidents'
    | '/locked'
    | '/login'
    | '/onboard'
    | '/platform'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/sites'
    | '/subscribe'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/hourly'
    | '/api/ingest/yolo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  IncidentsRoute: typeof IncidentsRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  PlatformRoute: typeof PlatformRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  SubscribeRoute: typeof SubscribeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronHourlyRoute: typeof ApiCronHourlyRoute
  ApiIngestYoloRoute: typeof ApiIngestYoloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/hourly': {
      id: '/api/cron/hourly'
      path: '/api/cron/hourly'
      fullPath: '/api/cron/hourly'
      preLoaderRoute: typeof ApiCronHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/yolo': {
      id: '/api/ingest/yolo'
      path: '/api/ingest/yolo'
      fullPath: '/api/ingest/yolo'
      preLoaderRoute: typeof ApiIngestYoloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  IncidentsRoute: IncidentsRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  PlatformRoute: PlatformRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  SubscribeRoute: SubscribeRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronHourlyRoute: ApiCronHourlyRoute,
  ApiIngestYoloRoute: ApiIngestYoloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
